CREATE DATABASE changi_dev;

CREATE TABLE `Category` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,

    `createdOn` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedOn` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` INT(1) NOT NULL DEFAULT 0,
    `deletedOn` TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE `Item` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `categoryID` INT NOT NULL,
    `name` VARCHAR(255) NULL,
    `price` DECIMAL(14, 2) NULL DEFAULT 0,

    `createdOn` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedOn` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` INT(1) NOT NULL DEFAULT 0,
    `deletedOn` TIMESTAMP NULL DEFAULT NULL,

    FOREIGN KEY (`categoryID`) REFERENCES Category(`id`)
);